export const countries = [
    'Argentina',
    'Armenia',
    'Belize',
    'Madagascar',
    'Canada',
    'China',
    'Costa Rica',
    'Dominica',
    'Egypt',
    'Ethiopia',
    'France',
    'Germany',
    'Haiti',
    'Hungary',
    'India',
    'Chile',
    'Kenya',
    'Liberia',
    'Brazil',
    'Mexico',
];